version: "3.8"

services:
  postgresql:
    image: postgres:latest
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5

  app:
    image: hugogc/realworldapp-for-test-automation:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      PORT: 3001
      JWT_KEY: supersecretkey
      DEV_DB_USERNAME: postgres
      DEV_DB_PASSWORD: postgres
      DEV_DB_NAME: db_dev
      DEV_DB_HOSTNAME: postgresql
      DEV_DB_DIALECT: postgres

volumes:
  postgres-data:
    driver: local
